
name: photomerge
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.1+2

environment:
  sdk: ^3.6.1


dependencies:
  flutter:
    sdk: flutter
  image: ^4.0.17
  path_provider: ^2.1.2
  permission_handler: ^11.0.1
  cupertino_icons: ^1.0.8
  image_picker: ^1.1.2
  http: ^1.3.0
  path: ^1.8.3
  firebase_core: ^3.10.1
  firebase_auth: ^5.4.1
  cloud_firestore: ^5.6.6
  cloudinary_public: ^0.23.1
  cached_network_image: ^3.4.1
  flutter_image_gallery_saver: ^0.0.2
  jiffy: ^6.4.3
  palette_generator: ^0.3.3+6
  async: ^2.11.0
  image_cropper: ^9.1.0
  firebase_storage: ^12.4.5
  url_launcher: ^6.3.1
  awesome_notifications: ^0.10.1
  device_info_plus: ^11.3.0
  carousel_slider: ^5.0.0
  shimmer: ^3.0.0
  share_plus: ^11.0.0
  provider: ^6.1.5
  google_fonts: ^6.2.1
  youtube_player_flutter: ^9.1.1
  flutter_staggered_grid_view: ^0.7.0
  lottie: ^2.6.0
  flutter_staggered_animations: ^1.1.1
  pdf: ^3.11.3
  open_file: ^3.5.10
  flutter_secure_storage: ^9.2.4
  animate_do: ^4.2.0
  audio_service: ^0.18.18
  audio_session: ^0.2.2
  youtube_player_iframe: ^5.2.1
  no_screenshot: ^0.3.1
  



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo/bb-logo.png"


flutter_lints: ^5.0.0


# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
  - assets/animations/image_grid_loading.json
  - assets/animations/error.json
  - assets/animations/empty_gallery.json
  - assets/animations/logo.json
  - assets/animations/reg.json
  - assets/animations/image_generating.json
  - assets/images/
  - assets/animations/loading.json
  - assets/logo/bb-logo.png

    

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
